/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'

const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/_authenticated/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/_authenticated/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/_authenticated/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/chat': typeof AuthenticatedChatRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/saved': typeof AuthenticatedSavedRoute
}
export interface FileRoutesByTo {
  '/chat': typeof AuthenticatedChatRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/saved': typeof AuthenticatedSavedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/chat' | '/history' | '/saved'
  fileRoutesByTo: FileRoutesByTo
  to: '/chat' | '/history' | '/saved'
  id:
    | '__root__'
    | '/_authenticated/chat'
    | '/_authenticated/history'
    | '/_authenticated/saved'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
